name: Flutter CI/CD

on:
  push:
    branches:
      - local

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    - name: Install Dependencies
      run: flutter pub get

    - name: Build APK
      run: flutter build apk

    - name: Set Date and Time
      id: datetime
      run: echo "::set-output name=datetime::$(date +'%d%m%Y-%H:%M')"

    - name: Upload to S3
      uses: actions/upload-artifact@v2
      with:
        name: app-release
        path: build/app/outputs/flutter-apk/app-release.apk

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.LOCAL_PAYRUN_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.LOCAL_PAYRUN_AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.LOCAL_PAYRUN_AWS_REGION }} 

    - name: Upload to S3 Bucket
      run: |
        aws s3 cp build/app/outputs/flutter-apk/app-release.apk s3://payrun-local-app-build/${{ steps.datetime.outputs.datetime }}/app-release.apk
        
    - name: Set Teams Message
      id: teams_message
      run: echo "::set-output name=message::Download the APK [here](https://your-s3-bucket-name.s3.amazonaws.com/payrun-local-app-build/${{ steps.datetime.outputs.datetime }}/app-release.apk)"

    - name: Send to Microsoft Teams
      uses: mshick/action-microsoft-teams@v0.5
      with:
        webhook-url: https://gainmedia.webhook.office.com/webhookb2/fe23f5fe-c652-4b7c-b277-eb724145aab3@14a3762e-7aff-45dd-a271-abbd15b79d9c/IncomingWebhook/2c7e366d6403490ea75df3ecc4b9a20b/d5d5098d-5ff6-4c8e-ae2b-bca174902873
        message: ${{ steps.teams_message.outputs.message }}
